version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "php"