apiVersion: v2
appVersion: 0.0.1
name: traderfour-core
version: 0.0.1
description: A helm chart for traderfour core project
home: https://gitlab.com/traderfour/core
maintainers:
- name: Alireza Josheghani
  url: https://github.com/mrjosh
sources:
- https://gitlab.com/traderfour/core
type: application
