<?php

namespace App\Enums\V1\FinancialEngineering;

use App\Enums\V1\EnumTrait;

enum RiskManagement: int
{
    use EnumTrait;

    // MAX_RISK_MODE
    case MAX_RISK_MODE_BALANCE = 30000;
    case MAX_RISK_MODE_EQUITY = 30001;

    // MAX_RISK_CALCULATION
    case MAX_RISK_CALCULATION_PERCENTAGE = 30010;
    case MAX_RISK_CALCULATION_AMOUNT = 30011;
    case MAX_RISK_CALCULATION_LOTS = 30012;


    // MAX_DAILY_RISK_MODE
    case MAX_DAILY_RISK_MODE_BALANCE = 30020;
    case MAX_DAILY_RISK_MODE_EQUITY = 30021;

    // MAX_DAILY_RISK_CALCULATION
    case MAX_DAILY_RISK_CALCULATION_PERCENTAGE = 30030;
    case MAX_DAILY_RISK_CALCULATION_AMOUNT = 30031;
    case MAX_DAILY_RISK_CALCULATION_LOTS = 30032;

    // MAX_DAILY_PROFIT_MODE
    case MAX_DAILY_PROFIT_MODE_BALANCE = 30040;
    case MAX_DAILY_PROFIT_MODE_EQUITY = 30041;

    // MAX_DAILY_PROFIT_CALCULATION
    case MAX_DAILY_PROFIT_CALCULATION_PERCENTAGE = 30050;
    case MAX_DAILY_PROFIT_CALCULATION_AMOUNT = 30051;
    case MAX_DAILY_PROFIT_CALCULATION_LOTS = 30052;

    // RISK_PER_CHART_MODE
    case RISK_PER_CHART_MODE_BALANCE = 30060;
    case RISK_PER_CHART_MODE_EQUITY = 30061;

    // RISK_PER_CHART_CALCULATION
    case RISK_PER_CHART_CALCULATION_PERCENTAGE = 30070;
    case RISK_PER_CHART_CALCULATION_AMOUNT = 30071;
    case RISK_PER_CHART_CALCULATION_LOTS = 30072;

    // RISK_PER_TRADE_MODE
    case RISK_PER_TRADE_MODE_BALANCE = 30080;
    case RISK_PER_TRADE_MODE_EQUITY = 30081;

    // RISK_PER_TRADE_CALCULATION
    case RISK_PER_TRADE_CALCULATION_PERCENTAGE = 30090;
    case RISK_PER_TRADE_CALCULATION_AMOUNT = 30091;
    case RISK_PER_TRADE_CALCULATION_LOTS = 30092;

    // STATUS
    case STATUS_ACTIVE = 30100;
    case STATUS_INACTIVE = 30101;



}
